# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'geetTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod "Kingfisher"
pod "SnapKit"
pod "R.swift"
  # Pods for geetTime

  target 'geetTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'geetTimeUITests' do
    # Pods for testing
  end

end
